### PR TITLE
Home page touch up

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**

### CODE REVIEW

**Comment by adamjonas** [comment]
image

I don't love this full width button. I'm ok to stack with a fixed width but not full width.

**Comment by Emmanuel-Develops** [comment]
> image
> 
> I don't love this full width button. I'm ok to stack with a fixed width but not full width.

alright. Try desktop

**Comment by Emmanuel-Develops** [comment]
Closes #27

**Comment by adamjonas** [comment]
If I click on this:
Screenshot 2023-07-17 at 4 35 10 PM

I get the wrong avatar, but the correct answer:
Screenshot 2023-07-17 at 4 34 57 PM

If I click into an avatar and ask a question, it will default to holocat

**Pull request merged**
